### ISSUE TITLE
Generate changelog fails when run.

### ISSUE THREAD

**Issue by mcpierce** [endaft/action-changelog#57]
I'm trying to incorporate this action into my build process and I'm seeing the following error when the step to generate the changelog happens. My action is setup as follows:

```
      - name: Create changelog
        id: changelog
        uses: endaft/action-changelog@v0.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/changelog-config.js
```

The configuration file used is:
```
module.exports = {
    types: [
        { types: ['enhancement'], label: '🎉 New Features' },
        { types: ['bugfix'], label: '🐛 Bugfixes' },
    ],

    excludeTypes: ['other'],

    /**
     * If implemented, performs note rendering.
     * @param {ChangelogCommitNote} notes An array of {@link ChangelogCommitNote}
     * @returns A `string` of the rendered notes.
     */
    renderNotes: (notes) => {
        return `\n## BREAKING CHANGES\n${notes
            .map((n) => {
                return `- due to [${n.commit.sha.substring(0, 6)}](${n.commit.url}): ${n.commit.subject}\n\n${n.text}\n\n`;
            })
            .join('')}`;
    },

    /**
     * If implemented, performs changelog type section rendering.
     * @param {string} label A label from the {@link ChangelogConfig.types config types}
     * @param {ChangelogCommit[]} commits An array of {@link ChangelogCommit changelog commits} which are responsive to the `label`.
     */
    renderTypeSection: (label, commits) => {
        return `\n## ${label}\n${commits
            .map((c) => {
                return `- ${c.scope ? `**${c.scope}:** ` : ''}${c.subject}`;
            })
            .join('\n')}\n`;
    },

    /**
     * If implemented, performs changelog rendering.
     * @param {string} release The tag name for the release. Ex: `v1.0.0`
     * @param {string} changes The formatted changes text from accumulating all {@link ChangelogConfig.renderTypeSection renderTypeSection} calls
     * @returns A `string` of the formatted, final changelog. There is no further processing after this call.
     */
    renderChangelog: (release, changes) => {
        return `# ${release} - ${new Date().toISOString().substring(0, 10)}\n\n` + changes + '\n\n';
    },
};

```

And the output is:

```

Run endaft/action-changelog@v0.0.5
  with:
    token: ***
    config_file: .github/changelog-config.js
  env:
    JAVA_HOME_11.0.20_x64: /opt/hostedtoolcache/jdk/11.0.20/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.20/x64
    JAVA_HOME_11_0_20_X64: /opt/hostedtoolcache/jdk/11.0.20/x64
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '/home/runner/work/comixed/comixed/.github/changelog-config.js'
Require stack:
- /home/runner/work/_actions/endaft/action-changelog/v0.0.5/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getConfig (/home/runner/work/_actions/endaft/action-changelog/v0.0.5/dist/index.js:10841:28)
    at handleAction (/home/runner/work/_actions/endaft/action-changelog/v0.0.5/dist/index.js:10851:20)
    at /home/runner/work/_actions/endaft/action-changelog/v0.0.5/dist/index.js:11172:24
    at /home/runner/work/_actions/endaft/action-changelog/v0.0.5/dist/index.js:11174:3
    at Object.<anonymous> (/home/runner/work/_actions/endaft/action-changelog/v0.0.5/dist/index.js:11177:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/endaft/action-changelog/v0.0.5/dist/index.js'
  ]
}
```

**Comment by mcpierce** [comment]
Sorry for the false alarm, the error (had I read it in more detail) was providing the wrong path to my configuration file.
